version: '3.8'

services:
  mongodb:
    image: mongo:8.0.0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456789
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local